version: '3'
services:
  es01:
    build:
      context: .
      dockerfile: elasticsearch.Dockerfile
    container_name: elasticsearch_python_tutorial_es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elasticsearch_python_tutorial
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.1
    container_name: elasticsearch_python_tutorial_kibana
    networks:
      - elasticsearch_python_tutorial
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: elasticsearch_python_tutorial_app
    volumes:
      - "./app:/app"
    networks:
      - elasticsearch_python_tutorial
    ports:
      - 5000:5000
    command: "python manage.py"

networks:
  elasticsearch_python_tutorial:
    driver: bridge
